### ISSUE TITLE
spcp oidc?

### ISSUE THREAD

**Issue by rjchow** [opengovsg/spcp-auth-client#74]
Do you guys have WIP or plans to migrate this to OIDC?

**Comment by LoneRifle** [comment]
No plans given that our counterparts at GDS already made [singpass-myinfo-oidc-helper](https://github.com/GovTechSG/singpass-myinfo-oidc-helper). It lacks CorpPass OIDC... though I've already filed GovTechSG/singpass-myinfo-oidc-helper#11 there.
